// console.log(username);
console.log("Learning PLaywright");
console.log("Learning PLaywright");
console.log("Learning PLaywright");
console.log("Learning PLaywright");
let username = "New";
console.log("Learning PLaywright");
console.log("Learning PLaywright");
console.log("Learning PLaywright");
console.log(username);